### ISSUE TITLE
Create Takedown Features

### ISSUE THREAD

**Issue by ivan-guo** [ivan-guo/OctaPicks#17]
Features:
_{Fighter A, Fighter B} x {average takedowns landed, takedown accuracy, takedown defence (% of opponent TD attempts that did not land), avg control time} x {R1, R2, R3, R4, R5, overall} x {last 3 fights, last 5 fights, alltime}_

These features should be represented in the form of # / per minute.

_{Fighter A, Fighter B} x {average takedowns landed differential, takedown accuracy differential, takedown defence differential, control time diff} x {R1, R2, R3, R4, R5, overall} x {last 3 fights, last 5 fights, alltime}_

These are per minute differentials.

Should end up being 288 extra features.

Create a new empty CSV file and create these new features by transforming ufc_men_stats_by_fight.csv
This will be a time-consuming operation - make sure to utilize vectorization to speed up the testing process.

Vectorization:
https://pythonspeed.com/articles/pandas-vectorization/

Pandas Apply (For use when vectorization is not possible):
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

Example (__create_home_adv_feats() uses apply, which is slower than __create_surface_env_feats() that uses vectorization):
https://github.com/ivan-guo/TennisModel/blob/main/processing.py

**Comment by straw-hat-gupta** [comment]
is it supposed to be average takedowns landed or td/min?

**Comment by straw-hat-gupta** [comment]
why is it only 240 isnt it 288?

**Comment by ivan-guo** [comment]
I updated it above, yes its supposed to be 288 I messed up the count lol. Also they are TD/min
