### ISSUE TITLE
Create W/L 5-rounder Features

### ISSUE THREAD

**Issue by ivan-guo** [ivan-guo/OctaPicks#4]
Feature:
_{Fighter A, Fighter B} x {wins in a 5-round fight, losses in a 5-round fight} x {R1, R2, R3, R4, R5, decision, overall} x {year, all-time}_

Should end up being 56 extra features.

Create a new empty CSV file and create these new features by transforming ufc_men_stats_by_fight.csv
This will be a time-consuming operation - make sure to utilize vectorization to speed up the testing process.

Vectorization:
https://pythonspeed.com/articles/pandas-vectorization/

Pandas Apply (For use when vectorization is not possible):
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

Example (__create_home_adv_feats() uses apply, which is slower than __create_surface_env_feats() that uses vectorization):
https://github.com/ivan-guo/TennisModel/blob/main/processing.py

**Comment by straw-hat-gupta** [comment]
This feature already is part of issue #3

**Comment by ivan-guo** [comment]
@straw-hat-gupta oh thats my bad, gonna close this then
